module.exports={
    devServer:{
        proxy:{
            "/my":{
                "target":"https://m.maoyan.com",
                "changeOrigin":true,
                "pathRewrite":{
                    "^/my":"/"
                }
            }
        }
    }
}